
package_name = "A"
repository_url = "repo.json"
repo_mode = "offline"

# package_name = "Microsoft.Extensions.Logging"
# repository_url = "https://api.nuget.org/v3/index.json"
# repo_mode = "online"

output_image = "graph.svg"
ascii_tree = true
filter_substring = ""